# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html
fos_ck_editor:
    configs:
        default:
            toolbar: "default_toolbar"

    toolbars:
        configs:
            default_toolbar: [ "@document"]

        items:
            document: [ 'Source', 'Cut', 'Copy', 'Paste', 'PasteText', 'PasteFromWord', '-', 'Undo', 'Redo', '-', 'Bold', 'Italic', 'Underline', 'Strike', 'CopyFormatting', 'RemoveFormat' ,'-', 'NumberedList', 'BulletedList', '-',  'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock', 'Maximize' ]

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'