# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        public_file_adapter:
            local:
                location: '%kernel.project_dir%/public/%uploads_dir_name%'
        private_file_adapter:
            local:
                location: '%kernel.project_dir%/public/%uploads_dir_name%'
    filesystems:
        public_file_filesystem:
            adapter: public_file_adapter
        private_file_filesystem:
            adapter: private_file_adapter
#            alias: League\Flysystem\Filesystem
